### PR TITLE
Update bluechi_0.6.0.bb - fix typo in required distro features

### PR DESCRIPTION
**Pull request by fwuehr1995**
Signed-off by: "Florian Wühr" <fwuehr@redhat.com>

### CODE REVIEW

**Comment by mwperina** [comment]
@odra Leonardo, could you please take a look?

**Comment by fwuehr1995** [comment]
Hi @mwperina ,

I was just taking part of today´s CentOS automotive SIG meeting and noticed that there was something going on with Yocto. I was just curious since I have been doing some work with Yocto in the past so I had a look what is going on there and noticed the typo in the variable. There is no such distro feature "systems" I strongly believe it shall be "systemd". 

I wasn´t aware of the need for registering to the eclipse foundation and currently don´t expect to be in touch with BlueChi too much so I won´t sign up for the Eclipse foundation for now. Never mind :)

**Comment by odra** [comment]
Sorry, just seeing it now. You care correct it's a typo. We have this eclipse account limitation unfortunately :\ 

let me open another pr with the change.

**Comment by mwperina** [comment]
Hi Florian,

I didn't want to discourage you to contribute to BlueChi, unfortunately being part of Eclipse SDV we need to conform to their contributor requirements.

Anyway thanks a lot for your contribution and if you will be interested in contributing to BlueChi in future, we would be glad to welcome you in our contributors team.

Regards,

Martin

@fwuehr1995

**Comment by fwuehr1995** [comment]
Hi @mwperina ,

you didn´t :) I now successfully set up an Eclipse account and signed the ECA so I should be good to go in the future. 

Regards,

Florian

**Pull request closed without merging**
